// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYiEA-_JMWWLQflXaFTlLVzCIrOyHL5go',
    appId: '1:966117097185:web:f13b3e8124305a7d8f01a0',
    messagingSenderId: '966117097185',
    projectId: 'medi-yello-care',
    authDomain: 'medi-yello-care.firebaseapp.com',
    storageBucket: 'medi-yello-care.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi4Z5v729xgEcYCy7k4fLHbTLBiX87Ytg',
    appId: '1:966117097185:android:037cb34ff93908a08f01a0',
    messagingSenderId: '966117097185',
    projectId: 'medi-yello-care',
    storageBucket: 'medi-yello-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbZiYI-YeonTci1MwtyeCUuTvSjk21eD4',
    appId: '1:966117097185:ios:0b55a541454edd078f01a0',
    messagingSenderId: '966117097185',
    projectId: 'medi-yello-care',
    storageBucket: 'medi-yello-care.firebasestorage.app',
    iosBundleId: 'com.codeurplus.mediYellocare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbZiYI-YeonTci1MwtyeCUuTvSjk21eD4',
    appId: '1:966117097185:ios:0b55a541454edd078f01a0',
    messagingSenderId: '966117097185',
    projectId: 'medi-yello-care',
    storageBucket: 'medi-yello-care.firebasestorage.app',
    iosBundleId: 'com.codeurplus.mediYellocare',
  );
}
